apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.name }}
webhooks:
  - name: mutation.webhook.svc
    clientConfig:
      service:
        name: {{ .Values.service.name }}
        namespace: {{ .Values.webhook.namespace }}
        path: "/mutate"
      caBundle: Cg==
    rules:
      - apiGroups: {{ .Values.webhook.rules.apiGroups }}
        apiVersions: {{ .Values.webhook.rules.apiVersions }}
        resources: {{ .Values.webhook.rules.resources }}
        operations: {{ .Values.webhook.rules.operations }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    matchPolicy: {{ .Values.webhook.matchPolicy }}
    objectSelector: {{ .Values.webhook.objectSelector | toYaml | nindent 6 }}
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    sideEffects: {{ .Values.webhook.sideEffects }}
