{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mutation-webhook
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mutation-webhook
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
roleRef:
  kind: Role
  name: mutation-webhook
  apiGroup: rbac.authorization.k8s.io
{{- end }}
